# Document:
# http://simiki.org/docs/configuration.html

url: 
title: tracholar's personal knownledgy wiki
keywords: technology, machine learning, data mining, economics, accounting
description: A wiki website of tracholar when I learning new knowledgy and technics.
author: tracholar

root: /wiki

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      